name: onest
description: Votre animal de compagnie accompagné

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  vrouter: ^1.2.0+21
  google_fonts: ^2.3.2
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  loading_indicator: ^3.0.3

dev_dependencies:
  flutter_app_name: ^0.1.1
  icons_launcher: ^1.1.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-bg.png"
  adaptive_icon_background: "#242424"
  adaptive_icon_foreground: "assets/logo-min.png"

flutter_native_splash:
  background_image: "assets/splashscreen_background.png"
  image: "assets/logo.png"

flutter_app_name:
  name: "O'nest"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
